### ISSUE TITLE
Get-SalesList

### ISSUE THREAD

**Issue by Mtndrew11** [Mtndrew11/python#4]
**Tasks:**
- [x] Gather data using BeautifulSoup and output data using tabulate
- [ ] Set zipcode for user (automatically or prompt tbd)
- [ ] Target specific items (listed below)
- [ ] Add multiple stores
- [ ] Save data in CSV format

**Stores:**
   - [ ] Aldi
   - [ ] Walmart
   - [ ] Food Lion
   - [ ] Harris Teeter
   - [ ] Costco

Items to target:
   - [ ] Milk
   - [ ] Eggs
   - [ ] Bread
   - [ ] Velveeta Cheese slices
   - [ ] Mayo
   - [ ] Black Beans
   - [ ] Deli ham
   - [ ] Oatmeal
   - [ ] Almond Milk
   - [ ] Lettuce
   - [ ] Meat
      - Chicken breast
      - Chicken thighs
      - Pork shoulder
      - Ground beef
      - Salmon
      - Brisket
      - Pork belly

**Process:**
1. Get zip code from user
2. Gather data from local grocery stores using zip code, using web scraping. 
3. Find the store with the cheapest price for the following items:

   - Milk
   - Eggs
   - Bread
   - Velveeta Cheese slices
   - Mayo
   - Black Beans
   - Deli ham
   - Oatmeal
   - Almond Milk
   - Lettuce
   - Meat
      - Chicken breast
      - Chicken thighs
      - Pork shoulder
      - Ground beef
      - Salmon
      - Brisket
      - Pork belly

**Comment by Mtndrew11** [comment]
Pulling data from Aldi sales items. Next step is to target specific items on a specific (local) store using zip code.

https://github.com/Mtndrew11/python/blob/dev/AldiPrices.py
